config/routes.rb
TestServer::Application.routes.draw do
  resources :comments

  resources :articles
  post 'articles/search' => 'articles#search', as: :articles_search

  root 'articles#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
  
  has_many :comments

  validates :title, presence: true
  validates :content, presence: true

  has_attached_file :attachment
  
  validates_attachment :attachment, size: { :in => 0..100.kilobytes }

    #######################################
   #       (Elasticsearch + Tire)        #   
  #######################################
  include Tire::Model::Search
  include Tire::Model::Callbacks

  # I am giving the index name according to env
  index_name("#{Rails.env}-articles")

  mapping _source: {excludes: ['comments']} do
    indexes :id, type: 'integer'
    indexes :author, type: 'string'
    indexes :title, type: 'string'
    indexes :content, type: 'string'
    indexes :comments do
      indexes :author, analyzer: 'snowball'
      indexes :message, analyzer: 'snowball'
      indexes :attachment_file_name, analyzer: 'snowball'
      indexes :attachment_content_type, analyzer: 'snowball'
      indexes :attachment_content, type: 'attachment'
    end
    indexes :attachment_file_name, type: 'string'
    indexes :attachment_content_type, type: 'string'
    indexes :attachment_content, type: 'attachment'
  end

  class << self
    
    def delete_search_index
      Tire.index(Article.index_name).delete
    end

  end
  
  def to_indexed_json
    {
      id: self.id,
      author: self.author,
      title: self.title,
      content: self.content,
      comments: comments.map { |c| {
          _id: c.id,
          author: c.author, 
          message: c.message,
          attachment_file_name: c.attachment_file_name,
          attachment_content_type: c.attachment_content_type,
          attachment_content: ( (!!c.attachment.path && File.exists?(c.attachment.path)) ? Base64.encode64(File.read(c.attachment.path)) : '' )
        }
      },
      attachment_file_name: self.attachment_file_name,
      attachment_content_type: self.attachment_content_type,
      attachment_content: ( (!!self.attachment.path && File.exists?(self.attachment.path)) ? Base64.encode64(File.read(self.attachment.path)) : '' )
    }.to_json
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article

  validates :author, presence: true
  validates :message, presence: true

  has_attached_file :attachment

  validates_attachment :attachment, size: { :in => 0..100.kilobytes }

    #######################################
   #       (Elasticsearch + Tire)        #   
  #######################################
  include Tire::Model::Search
  include Tire::Model::Callbacks

  # I am giving the index name according to env
  index_name("#{Rails.env}-comments")

  after_save lambda { self.article.update_index }
  after_destroy lambda { self.article.update_index }

  mapping do
    indexes :id, type: 'integer'
    indexes :author, type: 'string'
    indexes :message, type: 'string'
    indexes :created_at, type: 'date', :include_in_all => false
    indexes :updated_at, type: 'date', :include_in_all => false
    indexes :attachment_file_name, type: 'string'
    indexes :attachment_content_type, type: 'string'
    indexes :attachment_content, type: 'attachment'
  end

  class << self
    
    def delete_search_index
      Tire.index(Comment.index_name).delete
    end

  end

  def to_indexed_json
    {
      author: self.author,
      message: self.message,
      attachment_file_name: self.attachment_file_name,
      attachment_content_type: self.attachment_content_type,
      attachment_content: ( (!!self.attachment.path && File.exists?(self.attachment.path)) ? Base64.encode64(File.read(self.attachment.path)) : '' )
    }.to_json
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles ||= Article.all.paginate(page: params[:page])
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @comment = Comment.new
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render action: 'show', status: :created, location: @article }
      else
        format.html { render action: 'new' }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url }
      format.json { head :no_content }
    end
  end

  # this is where search is gonna happen
  def search
    if !params[:query]
      @articles = Article.all.paginate(page: params[:page])
    else 
      @articles = Article.search("*"+params[:query]+"*", load: true).results.paginate(page: params[:page])
    end
    respond_to do |format|
      format.html { render 'index' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :content, :author, :attachment)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all.paginate(page: params[:page], per_page: 5)
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to :back, notice: 'Comment was successfully created.' }
        format.json { render action: 'show', status: :created, location: @comment }
      else
        format.html { redirect_to :back }
        # format.html { render action: 'new' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to :back }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:author, :message, :article_id, :attachment)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :attachment %><br>
    <%= f.file_field :attachment %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/_no_results.html.erb
<h1>
  <p id="warning">No results found</p>
</h1>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Test listing articles</h1>

<div class="search">
  <%= form_tag articles_search_path do %>
    <%= text_field_tag :query, params[:query], hint: 'Search', placeholder: 'Search', autofocus: true %>
    <%= button_tag 'Search', class: 'btn' %>
    <%= link_to 'Clear', articles_path %>
  <% end %>
</div>

<%= link_to 'New Article', new_article_path %>

<% if @articles %>
  <%= will_paginate @articles %>
  <br/>
  <table>

    <tbody>
      <% @articles.each do |article| %>
        <tr>
          <td>
            <h2>
              <strong><%= link_to article.title, article_path(article) %></strong>
            </h2>
          </td>
        </tr>
        <tr>
          <td>Author:</td>
          <td><%= article.author %></td>
        </tr>
        <tr>
          <td colspan='2'><%= article.content %></td>
        </tr>
        <% if article.attachment_file_name %>
          <tr>
            <td>
              Attachment:
            </td>
            <td>
              <%= link_to article.attachment_file_name, article.attachment.url %>
            </td>
          </tr>
        <% end %>
        <tr>
          <td>
            Comments count:
          </td>
          
          <td>
            <%= article.comments.try(:count) %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br/>
  <br/>
  <%= will_paginate @articles %>
<% else %>
  <%= render partial: 'no_results' %>
<% end %>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Destroy', @article, method: :delete, data: { confirm: 'Are you sure?' } %> |
<%= link_to 'Back', articles_path %>

<p id="notice"><%= notice %></p>

<p>
  <h2><strong><%= @article.title %></strong></h2>
</p>

<p>
  <strong>Author:</strong>
  <%= @article.author %>
</p>

<p>
  <%= @article.content %>
</p>

<% if @article.attachment_file_name %>
  <p>
    <%= link_to @article.attachment_file_name, @article.attachment.url %>
  </p>
<% end %>



<p>
  <h2><strong>Comments</strong></h2>
</p>

<% @article.comments.each do |comment| %>
  <div class="frame">
    <p>
      <strong>Author:</strong>
      <%= comment.author %>
    </p>

    <p>
      <strong>Message:</strong>
      <%= comment.message %>
    </p>

    <% if comment.attachment_file_name %>
      <p>
        <%= link_to comment.attachment_file_name, comment.attachment.url %>
      </p>
    <% end %>

    <p>
      <%= link_to 'delete', comment, method: :delete, data: { confirm: 'Are you sure?' }  %>
    </p>
  </div>
<% end %>

<p>
  <h3><strong>New Comment:</strong></h3>
</p>
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :message %><br>
    <%= f.text_area :message %>
  </div>
  <div class="field">
    <%= f.label :attachment %><br>
    <%= f.file_field :attachment %>
  </div>
    <%= f.hidden_field :article_id, value: @article.id %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :message %><br>
    <%= f.text_area :message %>
  </div>
  <div class="field">
    <%= f.label :article_id %><br>
    <%= f.text_field :article_id %>
  </div>
  <div class="field">
    <%= f.label :attachment %><br>
    <%= f.file_field :attachment %>
  </div>

  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <thead>
    <tr>
      <th>Author</th>
      <th>Message</th>
      <th>Article</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.author %></td>
        <td><%= comment.message %></td>
        <td><%= comment.article %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Author:</strong>
  <%= @comment.author %>
</p>

<p>
  <strong>Message:</strong>
  <%= @comment.message %>
</p>

<p>
  <strong>Article:</strong>
  <%= @comment.article %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TestServer</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="middle">
  <%= yield %>
</div>

</body>
</html>